### ISSUE TITLE
Credit lovelace-ios-themes

### ISSUE THREAD

**Issue by basnijholt** [Kibibit/hass-kibibit-theme#18]
Hi @Thatkookooguy,

Nice theme!

I believe that this theme is largely based on https://github.com/basnijholt/lovelace-ios-themes#overview, I even see traces of my comments in [`themes/kibibit.yaml`](https://github.com/Kibibit/hass-kibibit-theme/blob/next/themes/kibibit.yaml) ;) 

I think it would be appropriate to link to that repo [here](https://github.com/Kibibit/hass-kibibit-theme#credits).

**Comment by Thatkookooguy** [comment]
Hi @basnijholt ! sorry about that! I actually based this on a Reddit post (you can see the post at the end of my readme.md since I like to give credit when credit's due :-)).
But I might have used your theme as an example of how to include multiple themes inside the same YAML and used your organized code as a template.

I added credit under the credit to henrik's post :-)

Nice to virtual meet you! :-)

**Comment by Thatkookooguy** [comment]
@basnijholt added! let me know if that's fine with you :-)

**Comment by Thatkookooguy** [comment]
oh and check out [kb-frosted-cards](https://github.com/kibibit/kb-frosted-cards)! they give a blur effect to lovelace cards! might go well with your theme if your cards have an opacity lower than 1.

(you can recommend that in your readme as well if you want to :-) might be a good promotional relationship 😘 )
