### ISSUE TITLE
change font size

### ISSUE THREAD

**Issue by dartfrogdk** [Kibibit/hass-kibibit-theme#5]
Hi sorry for asking but how do i change the font size?

**Comment by Thatkookooguy** [comment]
@dartfrogdk can you elaborate a bit? is this a bug for the theme or are you just asking for yourself (self-configuration)?

**Comment by dartfrogdk** [comment]
selfconfigurarion sorry im new

**Comment by Thatkookooguy** [comment]
Doesn't seems like home assistant allows changing the font size inside a theme, so I'm not sure if there's a theme option for me to offer.

But as a semi-solution, you can just `ctrl`+`+` on windows to make everything relatively bigger on desktop. `cmd` instead of `ctrl` if you're on a mac.

The font size is the same for every theme. I can help you figure out how to change the font size for home assistant, but it's an issue not related to this theme.

**Comment by dartfrogdk** [comment]
Thank you, you theme look very nice

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
18.11.20
07.11.53

Den tir. 17. nov. 2020 kl. 23.38 skrev Neil Kalman <notifications@github.com
